[package]
name = "buffer-load-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["full"] }
chrono = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
reqwest = "0.12.9"
rand = {workspace = true}