name: Library Release Build

on:
  push:
    branches:
      - release-library/**

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64
          - aarch64

    name: Python Linux ${{ matrix.target }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: actions/setup-python@v5

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        working-directory: py
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter
          sccache: "true"
          manylinux: auto

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: py/dist/*

  macos:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64
          - aarch64

    name: Python macOS ${{ matrix.target }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: actions/setup-python@v5

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        working-directory: py
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter
          sccache: "true"

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: py/dist/*

  sdist:
    name: Python sdist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5

      - name: Build sdist
        uses: PyO3/maturin-action@v1
        working-directory: py
        with:
          command: sdist
          args: --out dist

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: py/dist/*
